### ISSUE TITLE
KeyError: 'QUART_SCHEMA_CONVERT_CASING'

### ISSUE THREAD

**Issue by sanderfoobar** [pgjones/quart-schema#57]
Got a strange error in one of my apps:

```text
[2023-09-08 00:18:09,216] ERROR in app: Exception on request POST /bla
Traceback (most recent call last):
  File "/home/foo/bar/venv/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/foo/bar/venv/lib/python3.10/site-packages/quart/app.py", line 1675, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/foo/bar/venv/lib/python3.10/site-packages/quart/app.py", line 1107, in handle_user_exception
    raise error
  File "/home/foo/bar/venv/lib/python3.10/site-packages/quart/app.py", line 1673, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/foo/bar/venv/lib/python3.10/site-packages/quart/app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/foo/bar/venv/lib/python3.10/site-packages/quart_schema/validation.py", line 163, in wrapper
    if current_app.config["QUART_SCHEMA_CONVERT_CASING"]:
KeyError: 'QUART_SCHEMA_CONVERT_CASING'
```

Solved it by ensuring the key is present:

```python
app = Quart(__name__)
app.config['QUART_SCHEMA_CONVERT_CASING'] = False
```

Should this be `.get()` ?

https://github.com/pgjones/quart-schema/blob/91e46e849507d80bdd952fec8fb0ddc4f3decba2/src/quart_schema/validation.py#L166C39-L166C39

**Comment by pgjones** [comment]
Are you initialising the extension?
```
app = Quart(__name__)
QuartSchema(app)
```
